/*
 * Template created by: Comrade Cobweb
 * File generated by: CobwebBrainfuck (https://github.com/comradecobweb/CobwebBrainfuck)
 *
 * Should work on C11 or higher. To compile it (on Linux) use: gcc template.c -o template.elf
 * It's similar on Windows. You can also compile it using GNU Make or CMake. Have fun!
 *
 * PS: If you want the compiler to work, don't edit/delete line 49 in compiler resources folder!
 */

#include <stdio.h>
#include <stdlib.h>
#include <limits.h>

#define MEMORY_SIZE 30000

int main();

void plus();

void minus();

void left_arrow();

void right_arrow();

void comma();

void dot();

/*
 * Brackets:
 *
 * while(memory[memory_pointer]) {
 *	some code
 * }
 */

int memory_pointer;
char *memory;

int main(void) {
	memory = (char *) malloc(sizeof memory * MEMORY_SIZE);
	if (!memory) {
		puts("Error: could not allocate memory!\n");
		return -1;
	}
	memory_pointer = 0;
//here
	return 0;
}

void plus() {
	if (memory[memory_pointer] == CHAR_MAX)
		memory[memory_pointer] = 0;
	else
		memory[memory_pointer]++;
}

void minus() {
	if (memory[memory_pointer] == 0)
		memory[memory_pointer] = CHAR_MAX;
	else
		memory[memory_pointer]--;
}

void left_arrow() {
	if (memory_pointer == 0)
		memory_pointer = MEMORY_SIZE - 1;
	else
		memory_pointer--;
}

void right_arrow() {
	if (memory_pointer == MEMORY_SIZE - 1)
		memory_pointer = 0;
	else
		memory_pointer++;
}

void comma() {
	scanf("%c", &memory[memory_pointer]);
}

void dot() {
	putchar(memory[memory_pointer]);
}